---
title: "Matriz sintomatologica"
author: "Miguel Pérez Barrero"
date: "2/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Matriz sintomatologica

Se busca construir una matriz de sintomas por usuario y semana

```{r}
base_dir <- '../../datasets/SocialEvolution/'

flu <- read.csv2(paste0(base_dir, 'FluSymptoms.csv'), sep = ',')

base <- parse_date_time('2007/12/30 00:00', 'y-m-d H:M')

flu_time <- flu %>% mutate(
               time = parse_date_time(time, "y-m-d H:M:S")
             ) %>%
             mutate(
                weekday = wday(time), 
                week = as.integer(round(difftime(time, base, units = "weeks"))),
                year_week = week(time),
                hour = hour(time),
                month = month(time), 
                year = year(time),
                year_day = yday(time)
             ) %>% filter(year >= 2008) %>% arrange(week, user_id) %>%
             ungroup()

symptoms_by_weeks <- flu_time %>% filter(year == 2009) %>% group_by(week, user_id) %>% 
  summarize(
    sore.throat.cough = sum(sore.throat.cough),
    runnynose.congestion.sneezing = sum(runnynose.congestion.sneezing),
    fever = sum(fever),              
    nausea.vomiting.diarrhea = sum(nausea.vomiting.diarrhea),     
    sad.depressed = sum(sad.depressed),             
    open.stressed = sum(open.stressed)
  ) %>% ungroup()

write.csv2(symptoms_by_weeks, "symptoms_by_weeks.csv", row.names = FALSE)
```

```{r}
symptoms_by_weeks
```


```{r}
summary(symptoms_by_weeks)
```

Construimos la rejilla completa para que funcionen el algoritmo de construcción de la matriz final como producto de matrices:

```{r}
grid.weeks <- 40:70
grid.users <- subjects$user_id
symptoms_full_grid <- expand.grid(week = grid.weeks, user_id = grid.users)
symptoms_full_grid$sore.throat.cough = 0
symptoms_full_grid$fever = 0
symptoms_full_grid$runnynose.congestion.sneezing = 0
symptoms_full_grid$nausea.vomiting.diarrhea = 0
symptoms_full_grid$sad.depressed = 0
symptoms_full_grid$open.stressed = 0

symptoms_full_grid
```
Combinamos los datos de la matriz real. En la práctica esto supone imputar con ceros los datos faltantes.

```{r}
symptoms_full_grid <- symptoms_full_grid %>%
  full_join(symptoms_by_weeks) %>%
  group_by(week, user_id) %>%
  summarise(
    sore.throat.cough = max(sore.throat.cough),
    fever = max(fever),
    runnynose.congestion.sneezing = max(runnynose.congestion.sneezing),
    nausea.vomiting.diarrhea = max(nausea.vomiting.diarrhea),
    sad.depressed = max(sad.depressed),
    open.stressed = max(open.stressed)
  ) %>% ungroup()
symptoms_full_grid %>% filter(runnynose.congestion.sneezing > 0)
```
Guardamos la matriz de sintomas

```{r}
write.csv2(symptoms_full_grid, "symptoms_full_grid.csv", row.names = FALSE)
```


