---
title: "TFM"
author: "Miguel Pérez Barrero"
date: "27/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Python


```{r librerias, warning=FALSE, message=FALSE, error=FALSE}
library(reticulate)
conda_create("r-reticulate")
use_condaenv("r-reticulate")
py_install("rpy2")
```

## Posicionamiento con Wifis

```{python}
import numpy as np

import pandas as pd
from matplotlib import pyplot as plt
from matplotlib.collections import LineCollection

from sklearn import manifold
from sklearn.metrics import euclidean_distances
from sklearn.decomposition import PCA

from os.path import join

print(np.abs(-12))
```

```{python}
from IPython.display import display

import rpy2.rinterface as rinterface
rinterface.initr()

from rpy2.robjects import pandas2ri
pandas2ri.activate()

import rpy2.robjects as robjects

r = robjects.r
pydisplaydf = r.source('pydisplaydf.r')[0]

base_dir = '../../datasets/SocialEvolution/'

wlan_py = pd.read_csv(join(base_dir, 'WLAN2.csv'))

wlan_py

display(pydisplaydf(wlan_py))
```


```{python}
base_dir = '../../datasets/SocialEvolution/'

wlan_py = pd.read_csv(join(base_dir, 'WLAN2.csv'))

wlan_py
```

